# Generated by Django 2.2.7 on 2019-11-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.IntegerField()),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=45)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictive.Device')),
            ],
            options={
                'db_table': 'search',
            },
        ),
    ]
